# Runs the "build" script from package.json and pushes build to GitHub

name: Build Profile
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build Profile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm i yarn -g
      - name: Run Build Script
        run: yarn && yarn build
      - name: Commit README.MD
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: README.MD
          commit_message: "chore: automated readme updates"
          push_options: --force
